version: 0.2
phases:
  pre_build:
    commands:
      - echo "Setting execution variables..."
      - ECR_URI=`echo ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com`
      - REPOSITORY_URI=`echo ${ECR_URI}/${IMAGE_REPO_NAME}`
      - echo "Logging execution variables:"
      - echo "  variable  ECR_URI=`echo ${ECR_URI}`"
      - echo "  variable  REPOSITORY_URI=`echo ${REPOSITORY_URI}`"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "Target image and tag name...  ${REPOSITORY_URI}:$IMAGE_TAG"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG ${REPOSITORY_URI}:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI}:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - echo "Image definitions content *should* be:"
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json