apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
metadata:
  name: grp3-cap2a-eks2 #cluster name
  region: us-west-2 #desired region
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.16.0
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true"}'
    resolveConflicts: overwrite
nodeGroups:
  - name: grp3-cap2a-eks2-ng-1 #cluster node group name
    instanceType: t3.small #desired instance type
    desiredCapacity: 1 #desired nodes count / capacity
    ssh:
      allow: false # if true - will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub #you can specify the public key path likr this as well