apiVersion: v1
kind: Service
metadata:
  name: grp3-cap2a-eks2-nlb
  annotations:
    kubernetes.io/aws-load-balancer-type: external
    kubernetes.io/aws-load-balancer-scheme: internet-facing
    kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grp3-cap2a-eks2
